version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 866435872654.dkr.ecr.ap-southeast-2.amazonaws.com

  build:
    commands:
      - echo Build started
      - docker build -t myapp .
      - docker tag myapp:latest 866435872654.dkr.ecr.ap-southeast-2.amazonaws.com/myapp:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 866435872654.dkr.ecr.ap-southeast-2.amazonaws.com/myapp:latest