version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin YOUR_ECR_URI

  build:
    commands:
      - echo Build started
      - docker build -t myapp .
      - docker tag myapp:latest YOUR_ECR_URI/myapp:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push YOUR_ECR_URI/myapp:latest